name: pathact
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hdf3f5d2_2
  - anndata=0.9.2=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.2=py310hca03da5_1001
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h1a28f6b_0
  - arrow-cpp=8.0.0=py310ha45eab8_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-common=0.6.8=h1a28f6b_0
  - aws-c-event-stream=0.1.6=hc377ac9_5
  - aws-checksums=0.1.11=h1a28f6b_1
  - aws-sdk-cpp=1.8.185=h4a942e0_0
  - babel=2.12.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osxarm64_openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=h313beb8_0
  - bokeh=3.1.1=py310h33ce5c2_0
  - boost-cpp=1.78.0=hb428463_0
  - bottleneck=1.3.5=py310h96f19d2_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py310h1a28f6b_1002
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2025.7.15=hca03da5_0
  - certifi=2025.8.3=py310hca03da5_0
  - cffi=1.15.1=py310h80987f9_3
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.7=py310hca03da5_0
  - cloudpickle=3.0.0=py310hca03da5_0
  - comm=0.1.2=py310hca03da5_0
  - contourpy=1.2.0=py310h48ca7d4_0
  - cryptography=39.0.1=py310h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py310h80987f9_0
  - dask-core=2024.5.0=py310hca03da5_0
  - debugpy=1.5.1=py310hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=py310hca03da5_0
  - et_xmlfile=1.1.0=py310hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h80987f9_3
  - glog=0.6.0=h6da1cb0_0
  - grpc-cpp=1.46.1=h8e4afa7_1
  - hdf5=1.12.1=h160e8cb_2
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2021.8.26=py310h48bc37f_2
  - imageio=2.33.1=py310hca03da5_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.19.2=py310h33ce5c2_0
  - ipympl=0.9.3=py310hca03da5_0
  - ipython=8.10.0=py310hca03da5_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=py310hca03da5_0
  - jedi=0.18.1=py310hca03da5_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.9=py310hca03da5_0
  - jupyter_core=5.2.0=py310hca03da5_0
  - jupyter_server=1.23.6=pyhd8ed1ab_0
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.19.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=py310hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - kiwisolver=1.4.4=py310h313beb8_0
  - kneed=0.8.5=pyhd8ed1ab_1
  - krb5=1.19.3=hf9b2bbe_0
  - lazy_loader=0.4=py310hca03da5_0
  - lcms2=2.12=hba8e193_0
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=3.0=hc377ac9_0
  - libabseil=20211102.0=cxx17_hc0b94f3_2
  - libaec=1.0.4=hc377ac9_1
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.87.0=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.10=hbae9a57_4
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=11_3_0_hd922786_28
  - libgfortran5=11.3.0=hdaf2cc0_28
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=hb80f160_2
  - libthrift=0.13.0=hd358383_6
  - libtiff=4.5.1=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=15.0.7=h7cfbb63_0
  - locket=1.0.0=py310hca03da5_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.1=py310h1a28f6b_0
  - matplotlib=3.7.2=py310hca03da5_0
  - matplotlib-base=3.7.2=py310h46d7db6_0
  - matplotlib-inline=0.1.6=py310hca03da5_0
  - matplotlib-venn=1.1.2=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbclassic=0.5.2=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py310hca03da5_0
  - networkx=3.3=py310hca03da5_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numexpr=2.8.4=py310hecc3335_0
  - numpy-base=1.23.5=py310haf87e8b_0
  - openblas=0.3.21=openmp_hf78f355_3
  - openjpeg=2.3.0=h7a6adac_2
  - openpyxl=3.1.5=py310h80987f9_0
  - openssl=1.1.1w=h1a28f6b_0
  - orc=1.7.4=hdca1487_1
  - packaging=22.0=py310hca03da5_0
  - pandoc=2.19.2=hce30654_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py310hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py310h3b245a6_0
  - pip=22.3.1=py310hca03da5_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=py310hca03da5_0
  - pooch=1.7.0=py310hca03da5_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=py310hca03da5_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=8.0.0=py310hf303d72_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pynndescent=0.5.10=py310hca03da5_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py310hca03da5_0
  - pyrsistent=0.18.0=py310h1a28f6b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=hc0d8a6c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywavelets=1.5.0=py310hbda83bc_0
  - pyyaml=6.0.1=py310h80987f9_0
  - pyzmq=23.2.0=py310hc377ac9_0
  - re2=2022.04.01=h6b3803e_0
  - readline=8.2=h1a28f6b_0
  - requests=2.28.2=pyhd8ed1ab_0
  - scanpy=1.10.2=pyhd8ed1ab_0
  - scikit-image=0.20.0=py310h313beb8_0
  - scikit-learn=1.3.0=py310h46d7db6_0
  - scipy=1.11.4=py310h20cbe94_0
  - seaborn=0.13.2=py310hca03da5_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h17c5cce_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.1=h7a7dc30_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stdlib-list=0.10.0=py310hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=py310hca03da5_0
  - tornado=6.2=py310h1a28f6b_0
  - traitlets=5.7.1=py310hca03da5_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - umap-learn=0.5.4=py310hca03da5_1
  - urllib3=1.26.14=pyhd8ed1ab_0
  - utf8proc=2.6.1=h1a28f6b_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.38.4=py310hca03da5_0
  - widgetsnbextension=4.0.5=py310hca03da5_0
  - xyzservices=2022.9.0=py310hca03da5_1
  - xz=5.2.10=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zfp=0.5.5=hc377ac9_6
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.2=h8574219_0
  - pip:
      - aiobotocore==2.5.4
      - aiohttp==3.8.6
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - archs4py==0.2.19
      - async-timeout==4.0.3
      - biomart==0.9.2
      - biopython==1.84
      - biothings-client==0.3.0
      - botocore==1.31.17
      - bs4==0.0.2
      - colorcet==3.0.1
      - ec==0.0.0
      - frozenlist==1.4.0
      - fsspec==2023.5.0
      - h5py==3.8.0
      - igraph==0.11.9
      - iqplot==0.3.2
      - jmespath==1.0.1
      - kb-python==0.29.0
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - loess==2.1.2
      - loompy==3.0.7
      - lxml==5.3.0
      - multidict==6.0.4
      - mx==0.0.0
      - mygene==3.2.2
      - ngs-tools==1.8.6
      - numba==0.58.1
      - numpy==1.24.3
      - numpy-groupies==0.11.2
      - optimparallel==0.1.3
      - pandas==2.0.2
      - param==1.12.3
      - patsy==0.5.3
      - plotbin==3.1.5
      - plotly==5.24.1
      - progress==1.6
      - pyct==0.5.0
      - pysam==0.22.1
      - qnorm==0.8.1
      - s3fs==2023.5.0
      - setuptools==67.8.0
      - shortuuid==1.0.13
      - statsmodels==0.14.0
      - tenacity==9.0.0
      - texttable==1.7.0
      - tqdm==4.65.0
      - wget==3.2
      - wrapt==1.15.0
      - xalign==0.1.74
      - xarray==2023.2.0
      - yarl==1.9.2
prefix: /Users/nicholasmarkarian/miniconda3/envs/pathact
